version: '3.8'

services:
  app:
    tty: true
    stdin_open: true
    build:
      context: "."
      dockerfile: ./docker/Dockerfile
    volumes:
    # - ./metrics.txt:/usr/share/nginx/metrics/metrics.txt
    - ./test:/root/nfs-storage
    environment:
      DIRECTORY: /root/nfs-storage
      METRICS_FILE_PATH: /usr/share/nginx/metrics
    ports:
    - "80:80"