apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-disk-usage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-disk-usage
      app.kubernetes.io/instance: nfs-disk-usage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs-disk-usage
        app.kubernetes.io/instance: nfs-disk-usage
    spec:
      nodeName: worker1
      containers:
      - name: app
        image: tungtt1006/nfs-disk-usage
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        env:
          - name: DIRECTORY
            value: /root/nfs-storage
          - name: METRICS_FILE_PATH
            value: /usr/share/nginx/metrics
        volumeMounts:
          - name: nfs-directory
            mountPath: /root/nfs-storage
        readinessProbe:
          exec:
            command:
            - ls
            - -d
            - $path/*/
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - ls
            - -d
            - $path/*/
          initialDelaySeconds: 20
          periodSeconds: 5
        resources: {}
      volumes:
        - name: nfs-directory
          hostPath:
            path: <nfs-mount-path-on-node>
