apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-disk-usage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-disk-usage
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs-disk-usage
    spec:
      nodeName: worker1
      containers:
      - name: app
        image: tungtt1006/nfs-disk-usage
        env:
          - name: DIRECTORY
            value: /root/test
        volumeMounts:
          - name: nfs-directory
            mountPath: /root/test
      volumes:
        - name: nfs-directory
          emptyDir: {}
