apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nfs-disk-usage
spec:
  endpoints:
  - interval: 70s
    path: /metrics.txt
    port: http
    metricRelabelings:
      - sourceLabels:
        - volume
        action: replace
        regex: '/root/nfs-storage/(.*)-(pvc-.*)/'
        replacement: '$1'
        targetLabel: persistentvolumeclaim
      - sourceLabels:
        - volume
        action: replace
        regex: '/root/nfs-storage/(.*)-(pvc-.*)/'
        replacement: '$2'
        targetLabel: persistentvolume
      - regex: 'volume'
        action: labeldrop
  selector:
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - 'false'
    matchLabels:
      app.kubernetes.io/name: nfs-disk-usage
      app.kubernetes.io/instance: nfs-disk-usage